// Project metadata for seeding. This is a LIST — every object in it is seeded
// when you run `npm run seed-projects` (or filter to one via `npm run
// seed-projects <folder>`).
//
// For each project:
//   - `folder` must match a folder in scripts/images-to-upload/ holding its
//     screenshots. Images upload flat to the bucket root, so filenames must be
//     unique across all projects.
//   - `image_urls` are NOT defined here — they are derived from the uploaded
//     images.
//   - Set project_url / repo_url / completed_at to null if not applicable.

export const projectData = [
  {
    folder: "shape-mobile",
    title: "S.H.A.P.E: Mobile Learning Application for Special Needs Education",
    description:
      "S.H.A.P.E is an offline-capable mobile learning app for Special Needs Education, featuring 20+ interactive games, progress tracking, and an awards system, integrated with a web-based teacher management platform.",
    problems: [
      "No internet connection available for learning",
      "Few teachers can teach Filipino Sign Language",
      "Students feel unmotivated to study",
    ],
    solutions: [
      "Offline gameplay functionality",
      "Interactive Filipino Sign Language games",
      "Interactive educational games",
    ],
    features: [
      "Offline gameplay functionality",
      "Interactive educational activities through gamification",
      "Student progress tracking",
      "Awards and achievement system",
    ],
    tech_stack: ["Flutter", "Dart", "Flame Engine", "SQLite", "Git & GitHub"],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/shape_mobile",
    completed_at: "2025-12-01",
  },
  {
    folder: "shape-website",
    title: "S.H.A.P.E Admin & Learning Management System",
    description:
      "S.H.A.P.E Admin & LMS is the web platform for teachers and admins to manage lessons, grading, student progress, and awards for the S.H.A.P.E ecosystem, with automated weekly reports.",
    problems: [
      "Parents can't always bring their child to school",
      "Students lose interest quickly",
      "Parents aren't notified when their child needs to complete an activity",
    ],
    solutions: [
      "Teachers can give lessons/activities even at home",
      "Awards and achievement system",
      "Automated weekly parent emails",
    ],
    features: [
      "Lesson and activity management",
      "Student monitoring",
      "Automated grading system",
      "Awards and achievement management",
      "Semester and curriculum management",
      "Teacher and admin role management",
      "Weekly Automated Email",
      "Exportable grades, student list, etc",
      "Automated student grading",
    ],
    tech_stack: [
      "Laravel",
      "Livewire",
      "PHP",
      "MySQL",
      "Tailwind CSS",
      "Git & GitHub",
    ],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/shape-website",
    completed_at: "2025-12-01",
  },
  {
    folder: "chlsmartsolution",
    title: "CHL SmartSolutions",
    description:
      "CHL SmartSolutions is a role-based eCommerce and business management platform handling inventory, orders, service tasks, expenses, and reporting for admins, cashiers, technicians, and customers.",
    problems: [
      "Product stock levels get lost track of",
      "Expenses aren't tracked",
      "Order transaction receipts get lost",
    ],
    solutions: [
      "Inventory management with stock notifications",
      "Expense tracking",
      "Order management system",
    ],
    features: [
      "Role-based access control (Admin, Cashier, Technician, Customer)",
      "Inventory management system with stock tracking and updates",
      "Online order processing and tracking system",
      "Walk-in customer transaction system for cashiers",
      "Service task management and assignment for technicians",
      "Content Management System (CMS) for products and pages",
      "Sales tracking and reporting dashboard",
      "Expenses tracking and financial monitoring module",
      "Real-time order, sales, and staff activity monitoring",
      "Exportable reports (CSV/PDF format support)",
    ],
    tech_stack: ["Laravel", "Livewire", "PHP", "MySQL", "Git & GitHub"],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/chlsmartsolutions",
    completed_at: "2025-11-01",
  },
  {
    folder: "windshieldrvs",
    title: "WindShieldRVS",
    description:
      "WindShieldRVS is a web-based system that evaluates one-storey houses for wind vulnerability, automatically generating risk ratings with location mapping and exportable PDF reports.",
    problems: ["Homeowners can't tell if their house is vulnerable to strong winds"],
    solutions: ["Automated vulnerability and rating generation"],
    features: [
      "Automated vulnerability rating generation",
      "Strong wind risk evaluation system",
      "House location tracking and mapping",
      "Admin dashboard for monitoring assessment data",
      "Responsive web interface for multiple devices",
      "Exportable reports in PDF format",
    ],
    tech_stack: ["Laravel", "Livewire", "PHP", "MySQL", "Git & GitHub"],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/windshieldrvs",
    completed_at: "2025-12-01",
  },
  {
    folder: "carscanai",
    title: "CarScanAI: Car Brand Recognition System",
    description:
      "CarScanAI is an AI-powered web app that recognizes 15+ car brands from uploaded images in real time using a custom-trained deep learning model.",
    problems: [],
    solutions: [],
    features: [
      "Custom-trained AI model for car brand recognition",
      "Image classification using deep learning",
      "Supports 15+ car brands with high accuracy prediction",
      "Real-time prediction results from uploaded images",
    ],
    tech_stack: [
      "Python",
      "TensorFlow",
      "HTML",
      "Tailwind CSS",
      "JavaScript",
      "Git & GitHub",
      "Render",
    ],
    project_url: "https://carscanai.onrender.com/",
    repo_url: "https://github.com/Madrigal-Carl/CarScanAi",
    completed_at: "2025-12-01",
  },
  {
    folder: "tableo",
    title: "Tableo: Event Tabulation System",
    description:
      "Tableo is a web-based event tabulation system that automates score tallying, ranking, and tie-break resolution for competitions, with per-event PDF report exports.",
    problems: ["Manual score calculation", "Manual ranking"],
    solutions: ["Automated score tallying", "Automated ranking"],
    features: [
      "Judge scoring and submission system",
      "Automated score tallying and ranking",
      "Tie-score handling and resolution",
      "Event management system",
      "Real-time results computation",
      "Exportable reports per competition (PDF)",
    ],
    tech_stack: [
      "ReactJS",
      "ExpressJS",
      "Sequelize",
      "MySQL",
      "JavaScript",
      "Git & GitHub",
    ],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/Tableo",
    completed_at: "2026-03-01",
  },
  {
    folder: "swiftdocs",
    title: "SwiftDocs: Online Document Request System",
    description:
      "SwiftDocs is a web-based system for students to request and track academic documents online, with role-based workflows and exportable reports for staff.",
    problems: [
      "Students can't track their requested documents",
      "Staff don't know the status/order of requests",
      "Requesting documents requires an onsite visit",
    ],
    solutions: [
      "Real-time request tracking",
      "Request aging visibility",
      "Online document requesting",
    ],
    features: [
      "Online document request system",
      "Real-time request tracking",
      "Role-based access control (Admin, RMO, Cashier)",
      "Document management system",
      "Document verification and release workflow",
      "Sales and analytics dashboard",
      "Exportable reports (PDF)",
    ],
    tech_stack: [
      "ReactJS",
      "ExpressJS",
      "Zustand",
      "Sequelize",
      "MySQL",
      "JavaScript",
      "Git & GitHub",
      "Docker",
    ],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/SwiftDocs",
    completed_at: "2026-04-01",
  },
  {
    folder: "task-manager",
    title: "Task Manager: Full-Stack CRUD Application",
    description:
      "Task Manager is a full-stack CRUD app for managing tasks with pagination, filtering, search, and form validation, built to practice React and backend integration.",
    problems: [],
    solutions: [],
    features: [
      "CRUD operations",
      "Pagination, filtering, and search",
      "Form validation",
      "TanStack Query caching",
      "Responsive design",
      "REST API integration",
    ],
    tech_stack: [
      "ReactJS",
      "Tailwind CSS",
      "TanStack Query",
      "React Hook Form",
      "Zod",
      "JavaScript",
      "Express.js",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "Git & GitHub",
    ],
    project_url: "https://task-manager-iota-peach.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/TaskManager",
    completed_at: "2026-06-20",
  },
  {
    folder: "agricentral",
    title: "AgriCentral: Agricultural Resource Management Platform",
    description:
      "AgriCentral is a centralized platform for agricultural offices to manage farmer registries, crops, livestock, equipment, and resource requests, with audit logs and real-time analytics.",
    problems: [
      "Hard to know who to prioritize for aid during disasters",
      "Unclear who currently holds a given livestock/equipment",
      "No way to verify seeds were distributed correctly",
    ],
    solutions: [
      "Farm and harvest recording with incident reporting",
      "Livestock and equipment audit logs",
      "Seed distribution tracking",
    ],
    features: [
      "Farmer profile and association registry",
      "Geo-tagged farm records with parcel-level detail",
      "Crop monitoring with yield estimate tracking",
      "Livestock inventory and distribution history",
      "Equipment tracking with ownership, usage, and maintenance logs",
      "Centralized resource request management (crops, equipment, livestock)",
      "Incident reporting for damages and disruptions",
      "Immutable audit logs for every action and decision",
      "Organization and cooperative management with role-based access control",
      "Real-time dashboard analytics across regions and operations",
      "Exportable reports for offices and decision-makers",
    ],
    tech_stack: [
      "ReactJS",
      "ExpressJS",
      "Node.js",
      "MongoDB",
      "TanStack Query",
      "Tailwind CSS",
      "JavaScript",
      "Brevo",
      "Lovable",
      "Render",
      "Vercel",
      "Git & GitHub",
      "Cloudinary",
      "Valkey",
    ],
    project_url: "https://agri-central-five.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/AgriCentral",
    completed_at: "2026-08-01",
  },
  {
    folder: "fport",
    title: "StackBook: Facebook-Style Developer Portfolio Website",
    description:
      "StackBook is a Facebook-style developer portfolio presenting projects as social posts, with guest likes, comments, and multi-photo galleries.",
    problems: [],
    solutions: [],
    features: [
      "Facebook-style profile and post feed UI",
      "Theater-mode post detail view with image gallery",
      "Multi-photo post grid layouts with lightbox",
      "Guest likes and comments via client-generated UUID",
      "Site-wide views and likes counters",
      "Supabase Storage-backed project images",
      "Responsive design",
    ],
    tech_stack: [
      "ReactJS",
      "Tailwind CSS",
      "JavaScript",
      "Express.js",
      "Node.js",
      "Supabase",
      "PostgreSQL",
      "Git & GitHub",
      "Vercel",
      "Render",
    ],
    project_url: "https://fport-jade.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/revamped-portfolio",
    completed_at: "2026-08-15",
  },
  {
    folder: "prsentry",
    title: "PRsentry: AI-Powered Pull Request Reviewer",
    description:
      "PRsentry is an AI-powered pull request reviewer (CLI + GitHub Action) that checks diffs against a custom style guide and posts validated review comments automatically.",
    problems: ["Manual PR reviewing is slow and inconsistent"],
    solutions: ["Automated PR review"],
    features: [
      "AI-powered PR review against a customizable style guide",
      "Interactive approve, always-approve, or reject workflow",
      "Configurable Gemini model selection (CLI flag, env var, or saved config)",
      "Automatic diff batching for large pull requests",
      "Rate-limit retries with exponential backoff",
      "Hallucinated-finding filtering against the actual diff",
      "Optional GitHub Action for automated reviews on every PR",
    ],
    tech_stack: [
      "Node.js",
      "Commander",
      "Octokit",
      "Google Gemini API",
      "Zod",
      "GitHub Actions",
      "Git & GitHub",
    ],
    project_url: "https://www.npmjs.com/package/prsentry",
    repo_url: "https://github.com/Madrigal-Carl/prsentry",
    completed_at: "2026-09-01",
  },
];
