// Project metadata for seeding. This is a LIST — every object in it is seeded
// when you run `npm run seed-projects` (or filter to one via `npm run
// seed-projects <folder>`).
//
// For each project:
//   - `folder` must match a folder in scripts/images-to-upload/ holding its
//     screenshots. Images upload flat to the bucket root, so filenames must be
//     unique across all projects.
//   - `image_urls` are NOT defined here — they are derived from the uploaded
//     images.
//   - Set project_url / repo_url / completed_at to null if not applicable.

export const projectData = [
  {
    folder: "shape-mobile",
    title: "S.H.A.P.E: Mobile Learning Application for Special Needs Education",
    description:
      "S.H.A.P.E is a mobile learning application developed for students under Special Needs Education (SNED). The application allows students to access educational activities and interactive games even without internet connection through offline functionality. It includes a total of 20+ interactive educational games designed to enhance learning engagement. Integrated with a web management system, teachers can upload lessons, monitor student progress, manage curriculum and semesters, and track achievements through an awards system. The platform also includes automated grading and progress tracking features.",
    features: [
      "Offline gameplay functionality",
      "Interactive educational activities through gamification",
      "Student progress tracking",
      "Awards and achievement system",
    ],
    tech_stack: ["Flutter", "Dart", "Flame Engine", "SQLite", "Git & GitHub"],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/shape_mobile",
    completed_at: "2025-12-01",
  },
  {
    folder: "shape-website",
    title: "S.H.A.P.E Admin & Learning Management System",
    description:
      "S.H.A.P.E Admin & Learning Management System is the web-based administrative platform for teachers and school administrators managing the S.H.A.P.E ecosystem. It centralizes lesson and activity management, letting teachers upload content and organize curriculum by semester, while automated grading and progress tracking reduce manual review work. Administrators can manage teacher and admin roles, monitor student performance across the system, and oversee an awards and achievement program that keeps students engaged. The platform also handles routine reporting automatically — sending weekly summary emails and generating exportable grade sheets, student lists, and other records on demand — all integrated directly with the mobile learning application.",
    features: [
      "Lesson and activity management",
      "Student monitoring",
      "Automated grading system",
      "Awards and achievement management",
      "Semester and curriculum management",
      "Teacher and admin role management",
      "Weekly Automated Email",
      "Exportable grades, student list, etc",
      "Automated student grading",
    ],
    tech_stack: [
      "Laravel",
      "Livewire",
      "PHP",
      "MySQL",
      "Tailwind CSS",
      "Git & GitHub",
    ],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/shape-website",
    completed_at: "2025-12-01",
  },
  {
    folder: "chlsmartsolution",
    title: "CHL SmartSolutions",
    description:
      "CHL SmartSolutions is a full-featured eCommerce and business management web application with role-based access for customers, cashiers, technicians, and administrators. It supports end-to-end operations through a built-in CMS for products and pages, inventory management with stock tracking, and both online order processing and walk-in cashier transactions. Technicians can be assigned and manage service tasks, while sales tracking, expense monitoring, and real-time activity dashboards give administrators visibility into performance and finances. Reports across sales, orders, and staff activity can be exported in CSV or PDF for further analysis.",
    features: [
      "Role-based access control (Admin, Cashier, Technician, Customer)",
      "Inventory management system with stock tracking and updates",
      "Online order processing and tracking system",
      "Walk-in customer transaction system for cashiers",
      "Service task management and assignment for technicians",
      "Content Management System (CMS) for products and pages",
      "Sales tracking and reporting dashboard",
      "Expenses tracking and financial monitoring module",
      "Real-time order, sales, and staff activity monitoring",
      "Exportable reports (CSV/PDF format support)",
    ],
    tech_stack: ["Laravel", "Livewire", "PHP", "MySQL", "Git & GitHub"],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/chlsmartsolutions",
    completed_at: "2025-11-01",
  },
  {
    folder: "windshieldrvs",
    title: "WindShieldRVS",
    description:
      "WindShieldRVS is a web-based house vulnerability assessment system that evaluates the structural risk of one-storey residential houses against strong winds. It applies structured evaluation logic to house data and automatically generates vulnerability risk ratings, helping users and administrators understand potential wind damage exposure. Location tracking and mapping tie each assessment to a specific house, while an admin dashboard lets reviewers monitor assessment data in real time. Results can be exported as PDF reports, and the interface is responsive across devices.",
    features: [
      "Automated vulnerability rating generation",
      "Strong wind risk evaluation system",
      "House location tracking and mapping",
      "Admin dashboard for monitoring assessment data",
      "Responsive web interface for multiple devices",
      "Exportable reports in PDF format",
    ],
    tech_stack: ["Laravel", "Livewire", "PHP", "MySQL", "Git & GitHub"],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/windshieldrvs",
    completed_at: "2025-12-01",
  },
  {
    folder: "carscanai",
    title: "CarScanAI: Car Brand Recognition System",
    description:
      "CarScanAI is a web-based AI-powered car brand recognition system built around a custom-trained image classification model. The model recognizes over 15 car brands from uploaded vehicle images with high accuracy, and a responsive web interface returns predictions in real time as soon as an image is submitted. The project covers the full pipeline end to end, from data preprocessing and model training through deployment, combining deep learning with a seamless user-facing experience.",
    features: [
      "Custom-trained AI model for car brand recognition",
      "Image classification using deep learning",
      "Supports 15+ car brands with high accuracy prediction",
      "Real-time prediction results from uploaded images",
    ],
    tech_stack: [
      "Python",
      "TensorFlow",
      "HTML",
      "Tailwind CSS",
      "JavaScript",
      "Git & GitHub",
      "Render",
    ],
    project_url: "https://carscanai.onrender.com/",
    repo_url: "https://github.com/Madrigal-Carl/CarScanAi",
    completed_at: "2025-12-01",
  },
  {
    folder: "tableo",
    title: "Tableo: Event Tabulation System",
    description:
      "Tableo is a web-based event tabulation system built to manage scoring, ranking, and result computation for competitions and organized events. Judges submit scores directly through the platform, which automatically tallies results in real time and applies ranking logic, including tie-break resolution, to keep standings accurate. Built-in event management tools and per-competition PDF report exports support transparent, efficient handling of results from scoring through to final release.",
    features: [
      "Judge scoring and submission system",
      "Automated score tallying and ranking",
      "Tie-score handling and resolution",
      "Event management system",
      "Real-time results computation",
      "Exportable reports per competition (PDF)",
    ],
    tech_stack: [
      "ReactJS",
      "ExpressJS",
      "Sequelize",
      "MySQL",
      "JavaScript",
      "Git & GitHub",
    ],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/Tableo",
    completed_at: "2026-03-01",
  },
  {
    folder: "swiftdocs",
    title: "SwiftDocs: Online Document Request System",
    description:
      "SwiftDocs is a web-based document request and tracking system that lets students request, process, and monitor academic documents entirely online. Role-based access for Admin, RMO, and Cashier structures each request's path from submission through verification, payment, and release, with real-time tracking keeping students informed along the way. The system includes a document management module for organizing records, plus a sales and analytics dashboard and exportable PDF reports for administrative oversight.",
    features: [
      "Online document request system",
      "Real-time request tracking",
      "Role-based access control (Admin, RMO, Cashier)",
      "Document management system",
      "Document verification and release workflow",
      "Sales and analytics dashboard",
      "Exportable reports (PDF)",
    ],
    tech_stack: [
      "ReactJS",
      "ExpressJS",
      "Zustand",
      "Sequelize",
      "MySQL",
      "JavaScript",
      "Git & GitHub",
      "Docker",
    ],
    project_url: null,
    repo_url: "https://github.com/Madrigal-Carl/SwiftDocs",
    completed_at: "2026-04-01",
  },
  {
    folder: "old-port",
    title: "Project Store: Portfolio Showcase Website",
    description:
      "Project Store is a portfolio showcase website for presenting projects, skills, and technologies in a clean, card-based interface inspired by the Google Play Store. The layout emphasizes clarity and accessibility, with a responsive project showcase that adapts across devices and a dedicated presentation of each project's technology stack, making it easy to browse work in an organized, visually engaging way.",
    features: [
      "Responsive project portfolio showcase",
      "Technology stack presentation",
    ],
    tech_stack: ["ReactJS", "Tailwind CSS", "JavaScript", "Git & GitHub", "Vercel"],
    project_url: "https://cm-portfolio-tan.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/Portfolio",
    completed_at: "2026-05-28",
  },
  {
    folder: "task-manager",
    title: "Task Manager: Full-Stack CRUD Application",
    description:
      "Task Manager is a full-stack task management application built to practice modern React development and backend API integration. It supports complete CRUD operations for tasks along with pagination, filtering, and search, backed by a REST API. TanStack Query handles server-state management and caching for efficient data fetching, while React Hook Form and Zod provide robust form validation. The interface is fully responsive, with the overall project focused on learning best practices for building maintainable, data-driven web applications.",
    features: [
      "CRUD operations",
      "Pagination, filtering, and search",
      "Form validation",
      "TanStack Query caching",
      "Responsive design",
      "REST API integration",
    ],
    tech_stack: [
      "ReactJS",
      "Tailwind CSS",
      "TanStack Query",
      "React Hook Form",
      "Zod",
      "JavaScript",
      "Express.js",
      "Node.js",
      "MongoDB",
      "Mongoose",
      "Git & GitHub",
    ],
    project_url: "https://task-manager-iota-peach.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/TaskManager",
    completed_at: "2026-06-20",
  },
  {
    folder: "agricentral",
    title: "AgriCentral: Agricultural Resource Management Platform",
    description:
      "AgriCentral is a centralized, role-based agricultural management platform built to move agricultural offices away from fragmented records and manual processes. It maintains farmer and cooperative registries alongside geo-tagged, parcel-level farm records, and tracks crops with yield estimates, livestock inventory and distribution history, and equipment ownership, usage, and maintenance. Resource requests for crops, equipment, and livestock are centralized alongside incident reporting for damages and disruptions, with immutable audit logs recording every action for accountability. Role-based access spans organizations and offices, while real-time dashboard analytics and exportable reports give officials clear visibility for faster, more transparent decisions across regions.",
    features: [
      "Farmer profile and association registry",
      "Geo-tagged farm records with parcel-level detail",
      "Crop monitoring with yield estimate tracking",
      "Livestock inventory and distribution history",
      "Equipment tracking with ownership, usage, and maintenance logs",
      "Centralized resource request management (crops, equipment, livestock)",
      "Incident reporting for damages and disruptions",
      "Immutable audit logs for every action and decision",
      "Organization and cooperative management with role-based access control",
      "Real-time dashboard analytics across regions and operations",
      "Exportable reports for offices and decision-makers",
    ],
    tech_stack: [
      "ReactJS",
      "ExpressJS",
      "Node.js",
      "MongoDB",
      "TanStack Query",
      "Tailwind CSS",
      "JavaScript",
      "Brevo",
      "Lovable",
      "Render",
      "Vercel",
      "Git & GitHub",
      "Cloudinary",
      "Valkey",
    ],
    project_url: "https://agri-central-five.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/AgriCentral",
    completed_at: "2026-08-01",
  },
  {
    folder: "fport",
    title: "StackBook: Facebook-Style Developer Portfolio Website",
    description:
      "StackBook is a Facebook-style developer portfolio that presents projects as social media posts. The frontend is built with React and Tailwind CSS, featuring a Facebook-inspired profile layout, a project feed with multi-photo galleries, and a theater-mode post detail view. The backend is an Express API backed by Supabase (PostgreSQL + Storage), where anonymous guests identified by a client-generated UUID can like projects and post comments, with Row Level Security enforcing public reads and guest inserts.",
    features: [
      "Facebook-style profile and post feed UI",
      "Theater-mode post detail view with image gallery",
      "Multi-photo post grid layouts with lightbox",
      "Guest likes and comments via client-generated UUID",
      "Site-wide views and likes counters",
      "Supabase Storage-backed project images",
      "Responsive design",
    ],
    tech_stack: [
      "ReactJS",
      "Tailwind CSS",
      "JavaScript",
      "Express.js",
      "Node.js",
      "Supabase",
      "PostgreSQL",
      "Git & GitHub",
      "Vercel",
      "Render",
    ],
    project_url: "https://fport-jade.vercel.app/",
    repo_url: "https://github.com/Madrigal-Carl/revamped-portfolio",
    completed_at: "2026-08-15",
  },
  {
    folder: "prsentry",
    title: "PRsentry: AI-Powered Pull Request Reviewer",
    description:
      "PRsentry is an AI-powered pull request reviewer available as a CLI tool and an optional GitHub Action. It fetches a pull request's diff via the GitHub API, checks it against a customizable, repo-specific style guide using Google's Gemini models, and posts findings back as inline PR comments — with an interactive approve, always-approve, or reject workflow so nothing gets posted without sign-off. Large diffs are automatically split and batched to stay within model context limits, Gemini calls retry with backoff on rate limits, and every finding is validated against the actual diff before posting to filter out anything the model hallucinated.",
    features: [
      "AI-powered PR review against a customizable style guide",
      "Interactive approve, always-approve, or reject workflow",
      "Configurable Gemini model selection (CLI flag, env var, or saved config)",
      "Automatic diff batching for large pull requests",
      "Rate-limit retries with exponential backoff",
      "Hallucinated-finding filtering against the actual diff",
      "Optional GitHub Action for automated reviews on every PR",
    ],
    tech_stack: [
      "Node.js",
      "Commander",
      "Octokit",
      "Google Gemini API",
      "Zod",
      "GitHub Actions",
      "Git & GitHub",
    ],
    project_url: "https://www.npmjs.com/package/prsentry",
    repo_url: "https://github.com/Madrigal-Carl/prsentry",
    completed_at: "2026-09-01",
  },
];
